name:

on: push

jobs:
  markdown-to-pdf:
    runs-on: ubuntu-18.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: ".dot -> [Graphviz] -> .eps"
        run: make images
      - name: "Markdown -> [pandoc] -> LaTeX "
        uses: docker://pandoc/core:2.17
        with:
          args: >- # allows you to break string into multiple lines
            spec.md
            --template include/spec-template.tex
            --syntax-definition include/firrtl.xml
            --syntax-definition include/ebnf.xml
            -r markdown+table_captions+inline_code_attributes+gfm_auto_identifiers
            --filter pandoc-crossref
            -o build/spec.tex
      - name: "LaTeX -> [TeX Live] -> PDF"
        uses: xu-cheng/texlive-action/small@v1
        with:
          run: latexmk -pdf spec.tex -output-directory=build
      - name: "Upload build directory"
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
          retention-days: 1
      - name: "Create Release if Tagged"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: build/spec.pdf
